version: "2.4"

services:
  base:
    build:
      context: .
      target: base
    command: python main.py
    volumes:
      - .:/app
    ports:
      - 8081:8081

  builder:
    build:
      context: .
      target: builder
    command: python main.py
    volumes:
      - .:/app
